networks:
  cbc:

volumes:
  mysql:

services:
  app:
    build:
      context: .
      dockerfile: build/apache/php-7.3/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/config/.env:/var/www/html/.env.template
      - ~/.composer/cache:/var/www/.composer/cache
    depends_on:
      - mysql
    networks:
      - cbc
    command: >
      sh -c "if [ ! -f /var/www/html/.env ]; then
        cp /var/www/html/.env.template /var/www/html/.env;
      fi &&
      composer install -o &&
      composer dump-autoload -o &&
      docker-php-entrypoint apache2-foreground"

  mysql:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --init-file=/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cbc
      MYSQL_USER: cbc
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d
    networks:
      - cbc