version: '3'

networks:
  cbc:

services:
  app:
    build:
      context: .
      dockerfile: build/apache/php-7.3/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
      - "5173:5173"
    volumes:
      - ./src:/var/www/html
      - ./.docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ~/.composer/cache:/var/www/.composer/cache
      - ~/.npm:/var/www/.npm
    depends_on:
      - mysql
    networks:
      - cbc

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: cbc
      MYSQL_USER: cbc
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: admin123
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - cbc